### ISSUE TITLE
"EXCEPTION while printing message" output for failing test

### ISSUE THREAD

**Issue by umrigar** [SWI-Prolog/swipl-devel#1057]
On swipl v 8.4.2, a failing test prints with an ugly _EXCEPTION while printing message_ output.  It works as expected on earlier version 8.2.4.  This may be related to this [stackoverflow issue](https://stackoverflow.com/questions/72355363/error-exception-while-printing-message-raised-type-error-on-plunit-run-tests).
[bug-report.txt](https://github.com/SWI-Prolog/swipl-devel/files/9780007/bug-report.txt)

**Comment by kamahen** [comment]
This works as expected with the development version (I built from the current github sources, but I'm 99.99% sure it'll give the same result from `ppa:swi-prolog/devel`):
```
$ swipl -t run_tests t.pl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.18-39-g984787a12-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

% PL-Unit: test_pred .
ERROR: /tmp/t.pl:9:
	test bad_print: failed

 done
% 1 test failed
% 1 tests passed
```

**Comment by umrigar** [comment]
Okay, thanks for getting to it so quickly.  So hopefully this problem will not recur in future versions and I am closing this out.

**Comment by kamahen** [comment]
This probably won't get fixed in the "stable" version (that is, it probably won't be backported from 8.5.x), until the next major version release (8.6.x). 
The general recommendation is to use the "development" version, which - despite the name - is quite stable and seldom has a significant regression. 
General discussion is here: https://swi-prolog.discourse.group/
