### ISSUE TITLE
Emscripten build with pcre

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/swipl-devel#1166]
It would be very useful if we could have an additional Emscripten target that supports pcre that we can also include as one of the builds in the npm distribution of swipl-wasm.

Presumably this would entail an additional set like https://github.com/SWI-Prolog/swipl-devel/blob/759e27387aae6689a6dc68a4be277d1904fe18ec/cmake/PackageSelection.cmake#L114-L115 and another build config in `EmscriptenTargets.cmake`?

**Comment by JanWielemaker** [comment]
I'm not in favor of yet another target.     We could do the same for all other extension, ending with 2^N wasm targets :cry:   We either decide to include it by default or not.   pcre is a big dependency on Linux, but that is claimed to mostly due to the JIT compilation support.    If it is small enough, let us include it, otherwise we can make it work and allow the user to use `-DSWIPL_PACKAGE_LIST=List` to select the desired list.

**Comment by jeswr** [comment]
The size impact is negligible; the files in swipl-wasm are

Without PCRE
```
$ ls -la
      53 Apr 13 06:02 swipl-bundle.d.ts
10545458 Apr 13 06:47 swipl-bundle.js
      53 Apr 13 06:02 swipl-bundle-no-data.d.ts
 2727544 Apr 13 06:46 swipl-bundle-no-data.js
      53 Apr 13 06:02 swipl.d.ts
  184985 Apr 13 06:47 swipl.js
 5831169 Apr 13 06:47 swipl-web.data
      53 Apr 13 06:02 swipl-web.d.ts
  184985 Apr 13 06:47 swipl-web.js
 1928669 Apr 13 06:47 swipl-web.wasm
```

With PCRE
```
$ ls -la
      53 Apr 13 06:02 swipl-bundle.d.ts
10594414 Apr 20 10:37 swipl-bundle.js
      53 Apr 13 06:02 swipl-bundle-no-data.d.ts
 2727552 Apr 20 10:35 swipl-bundle-no-data.js
      53 Apr 13 06:02 swipl.d.ts
  184983 Apr 20 10:37 swipl.js
 5867881 Apr 20 10:36 swipl-web.data
      53 Apr 13 06:02 swipl-web.d.ts
  184983 Apr 20 10:37 swipl-web.js
 1928675 Apr 20 10:37 swipl-web.wasm
```

Which means that for most consumers the bundle size they recieve will only increase by ~0.5%. I'll create a PR adding PCRE to the PackageSelection for WASM.
