### ISSUE TITLE
Rollback retract/1 change, possibly too risky.

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#163]
The current atomicity of erase/1 seems to be sufficient, to bootstrap
alternative realization of retract/1 such as:

```
retract_alt(V) :- var(V),
   throw(error(instantiation_error,_)).
retract_alt((H :- B)) :- !,
   clause(H, B, R), erase(R).
retract_alt(H) :-
   clause(H, true, R), erase(R).
``` 

But it seems a little bit to risky to override the retract/1 semantics,
after changing the erase/1 semantic. Reason: Too many Prolog systems
implement the old semantic, see below.

But the new erase/1 semantic and the old retract/1 semantic could
co-exist. The old semantic retract/1 can even be bootstrapped from 
the new erase/1 as follows:

```
retract(V) :- var(V),
   throw(error(instantiation_error,_)).
retract((H :- B)) :- !,
   clause(H, B, R), ignore(erase(R)).
retract(H) :-
   clause(H, true, R), ignore(erase(R)). 
```

Bye

P.S.: Here are the test results for many Prolog systems:

ISO core standard page 81, examples 8.9.3.4:

```
   :- dynamic insect/1.
   insect(ant).
   insect(bee). 
```

3) GNU Prolog 1.4.4 (64 bits)
   Compiled Apr 23 2013, 16:05:07 with cl

```
   ?- retract(insect(I)), write(I), nl,
   retract(insect(bee)), fail; true.
   ant
   bee

   yes
```

4) ECLiPSe Constraint Logic Programming System [kernel]
   Version 6.1 #222 (x86_64_nt), Thu Jul  7 16:02 2016

```
   [eclipse 3]: retract(insect(I)), write(I), nl,
   retract(insect(bee)), fail; true.
   ant
   bee

   I = I
   Yes (0.00s cpu)
```

5) Ciao 1.15-1781-g328b907: Wed Jun 19 00:06:05 PST 2013

```
   ?- retract(insect(I)), write(I), nl,
   retract(insect(bee)), fail; true.
   ant
   bee

   yes
```

6) B-Prolog Version 8.1, All rights reserved,
   (C) Afany Software 1994-2014.

```
   ?- retract(insect(I)), write(I), nl,
      retract(insect(bee)), fail; true.
   ant
   bee

   yes
```

**Comment by JanWielemaker** [comment]
I has some doubts about this.   It won't hurt many applications and I guess it is a borderline case wrt the logical update view.   Single threaded behaviour should remain compatible though.  There might be a way out for multi-threaded.

If threads do not retract using backtracking, but using once(retract(...)), we still have a race because the generation is established as the retract/1 call starts.    Possibly we can modify that such that threads competing on a retract make sure that one picks the generation when the clause still existed and the other the one after.

Not sure how easy/hard that is to implement.   It would be logically sound as both threads will do classical logical update view, only one is delayed a little at the start of the retract.   If it is easy to implement it might be worthwhile.  Otherwise my conclusion is that predicates are not designed for thread communication anyway and I opt for documenting the issue.

**Comment by JanWielemaker** [comment]
The implementation of my proposal appeared trivial as I discovered while cycling to the uni.   Updated accordingly.

**Comment by jburse** [comment]
Just skimmed over the changed source, some determinism check right? 

BTW: My pool test case for balance/3 predicate uses a non-deterministic 
multi-threaded retract/1, still won't work with this cludge.

Anyway I have changed the pool test case so that a helper predicate
retract_alt/1 is used, which uses clause/3 and erase/1.

**Comment by JanWielemaker** [comment]
No, only a test that if two threads retract the same clause on the first call it will re-sync its notion of the current generation.   You can't respect the logical update view and avoid duplicate answers using concurrent backtracking retract.  But then, why would you want to do that?   Database references are not part of ISO, so you can do whatever you want :)

**Comment by jburse** [comment]
Yeah, ISO doesn't handle database references, thats why I propose the rollback: Don't change retract/1 only erase/1. But now that you are at it, with re-syncs there can be also performance penalties. Feel free to test with the pool example.

It has now a cascaded retract. The second retract is not very interesting, since it will anyway only be done inside the same thread, the first retract is the ticked for the thread. But the second retract is nevertheless interesting since it is also concurrent, although for different vertical index regions.

See here:

% remove(-Integer)
remove(X) :-
   retract(pool(A, B)),
   Y is A * 22 + B,
   retract(subpool(A, B, C)),
   X is Y * 22 + C.

https://github.com/jburse/jekejeke-samples/blob/master/jekrun/benchdist/tests/swipool.p
