### ISSUE TITLE
Existence error escapes catch/3

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#198]
Please try with SWI 7.5:

<pre>
?- catch(test, E, true).
<b>ERROR: Undefined procedure: test/0 (DWIM could not correct goal)</b>
</pre>

For comparison, in GNU Prolog:

<pre>
| ?- catch(test, E, true).

<b>E = error(existence_error(procedure,test/0),top_level/0)</b>
</pre>

I would like to catch this error so that I can safely use for example:

<pre>
<b>catch</b>(el_unwrap(current_input), <b>error(existence_error(_,_), _)</b>, true)
</pre>

This is one way to correct #196 in a way that remains compatible with older SWI versions, and with those that are compiled without `libedit`.

**Comment by JanWielemaker** [comment]
The error is caused by the DWIM mechanism for correcting toplevel goals.  Your code runs fine anywhere but on the toplevel.  You can wrap a goal in call/1 to overrule DWIM.  Normally though,
I'd write

```
:- if(current_predicate(el_unwrap/3)).
...
```

And better, if you want to control input editing, set the prolog flag `readline` to one of `false`, `readline` or `editline`.
