### ISSUE TITLE
Combining options solutions/1 and relative_to/1 of absolute_file_name/3 gives incorrect behavior

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#205]
Options of `absolute_file_name/3` give unexpected results.  Example:

```
?- absolute_file_name('*.pl', X, [access(read),expand(true),relative_to('/home/wbeek/Data'),solutions(first)]).
X = '/home/wbeek/Git/plRdf/init.pl' ;
X = '/home/wbeek/Git/plRdf/pack.pl'.
```

I was expecting a single solution, because of option `solutions(first)`.

I was expecting Prolog files from directory `/home/wbeek/Data`, because of option `relative_to`, not Prolog files from the current working directory.

**Comment by JanWielemaker** [comment]
absolute_file_name/3 isn't really indented to be used that way, but it is surely not supposed to be nondet.
The `expand(true)` was introduced to deal with $VAR in file names, which used to be standard and was later removed to avoid ambiguity.  It now interprets the different solutions of the wildchart as choices, just like the choices provided by file_search_path/2.  Fixed with c2a6d5d3b7584a1f40fc1f51828a5399ffcc796e
