### ISSUE TITLE
setup_call_catcher_cleanup/4 does not catch exception

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#337]
Example:

<pre>
?- setup_call_catcher_cleanup(open_string('abc(', In),
                              read_term(In, Term, []),
                              Catcher,
                              close(In)).
<b>%@ ERROR: Stream <stream>(0x7fe7049050f0):1:4 Syntax error: Unexpected end of file
%@ ^  Call: (10) call(user:close(<stream>(0x7fe7049050f0))) ? abort
%@ % Execution Aborted</b>
</pre>

In contrast, using `catch/3`, I get:

<pre>
?- catch((open_string('abc(', In),
          read_term(In, Term, [])),
         Catcher,
         true).
<b>%@ Catcher = error(syntax_error(end_of_file), stream(<stream>(0x7fe7048056e0), 1, 4, 3)).</b>
</pre>

**Comment by JanWielemaker** [comment]
This is fine and probably a misconception caused by not-the-best-possible naming ...  This predicate is basically `setup_call_cleanup/3`, which also traps the debugger if the exception is not caught.  In addition
it passes _why_ the cleanup handler is called.  (failure, det success, cut, exception, exception
Goal has open choice points).
