### ISSUE TITLE
Undocumented random labeling options in CLP(FD)

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#398]
The followig works:

![image](https://user-images.githubusercontent.com/5411487/50540563-6a6b6800-0b94-11e9-9e43-2f22cbb07c1f.png)

But the option is not documented here:

http://www.swi-prolog.org/pldoc/doc_for?object=labeling/2

**Comment by jburse** [comment]
Juding from this SO answer, there are even more options than
only random_value/1. Maybe also random_variable/1. What does it do?

https://stackoverflow.com/q/8693788/502187

**Comment by triska** [comment]
`random_variable/1` selects a random variable at each step during labeling, when a variable needs to be picked.

I have consciously *not yet documented* these options: They are currently available only to initiate discussion of this feature and to gather feedback from interested application programmers. You cannot rely on undocumented CLP(FD) features to remain available or work as they currently work, so be careful when using these features.

Providing randomness and other extensions requires subtle guarantees to ensure logical&nbsp;purity and desirable declarative properties that are not&nbsp;yet fully clear. Currently, CLP(FD) is also not yet widely enough used to create sufficient feedback that sustainably supports such extensions. So, as a first step, I encourage application programmers to use the basic constraints. We can discuss extensions in a few&nbsp;years, under better conditions with a larger community that is interested in improving these areas.  I'll be there then, and am looking forward to it!

**Comment by jburse** [comment]
You can lookup the Jekejeke Prolog implementation. It uses random_permutation/1 (see for example SICStus) and it is complete. Means if you find a solution without random you also find it with random and vice versa. I will upload the source in the next days to GitHub.

**Comment by jburse** [comment]
Well what has now been implemented in Jekejeke Prolog, existed
already before for quite a long time. I don't know what you want 
to wait for and what your mysterious unclear issues should be.

> See here: indomain/2
> random: Try the enumeration in a random order. On backtracking, 
    the previously tested value is removed. This method uses random/1 to 
    create random numbers, use seed/1 before to make results reproducible.
    http://eclipseclp.org/doc/bips/lib/gfd_search/indomain-2.html

I guess its a good idea to adopt indomain/2, currently I have implemented
add random_indomain/1, and from this implemented random_label/1. See also here:

       *Domain Search  - CLP(FD)*
       http://www.jekejeke.ch/idatab/doclet/prod/en/docs/15_min/10_docu/02_reference/07_theory/03_finite/05_enum.html

**Comment by triska** [comment]
> it is beyond me what you want to wait for and what your mysterious unclear issues should be.

Here are a few examples:

Currently, to initiate discussion with interested parties, I have provided highly experimental support for two labeling options involving randomness:

- `random_variable(+Seed)`
- `random_value(+Seed)`

Importantly, these options take a random **`Seed`** that makes labeling deterministic while still allowing (pseudo-)random behaviour.

Now the questions start. Suppose I write:

`labeling([random_variable(A),random_value(B)], Vs)`

where `A #\= B`. Should this be an error? Or should `B` override `A`? Or vice versa? Or should the seeds be independent?

Further, what about parametrizing the random number generator? Should this be supported?

Should **user-provided** random number generators be supported? How should this interface look like?

Finally, the overarching question for all new labeling options: 

<blockquote>
How can we provide sufficient <b>flexibility</b> to incorporate user-defined search strategies, while <i>at the same time</i> still providing <b>guarantees</b> such as completeness and termination of <tt>labeling/2</tt>?
</blockquote>

This is related to other extensions such as backjumping, conflict-directed search etc.

I will never add a predicate `random_indomain/1`, since this depends on an **implicit** seed and is therefore impure. This would complicate reasoning over CLP(FD) programs to such an extent that it would become unattractive, and this is the opposite of where I want to take these extensions.

**Comment by jburse** [comment]
What do they do random_variable/1 and random_value/1? You only gave a bullet list with the names of two options, without any explanation what they do. Sorry can help, not enough information.

**Comment by jburse** [comment]
Completeness would be only affected if random would not mean random **permutation**, but something else. For example if random would mean limited sampling, then anyway there would be no be necessary exact completeness, maybe only some probabilistic guarantees, or only guarantees on

one particular side, like a probabilistic prime number test, which can reject a number with 100% confidence, but an accepted number has not 100% confidence. But from the reference I gave, the ECLiPSe indomain/2, it should be clear, that so far,

by random, only **permutation** was understood, and not sampling.

**Comment by triska** [comment]
Ideally, specifying a custom random number generator would be one specific instance of a more general mechanism to control the search via labeling options. The important question is: How can we *automatically* ensure all desirable properties while at the same time making the extension general enough to implement user-specified strategies. These are hard questions for which I first need to collect more feedback from interested application programmers. I have therefore not documented these highly experimental options, since I want to discuss them first with many more participants and experts.

The way they are now implemented is definitely not the last word on this topic, and if you use them please take into account that your code will break in the future. For the immediate future, that's all I can say about this&nbsp;topic.

**Comment by jburse** [comment]
Well you can lookup how random_permutation is implemented:

random_permutation_(List, RandomPermutation) :-
    key_random(List, Keyed),
    keysort(Keyed, Sorted),
    pairs_values(Sorted, RandomPermutation).

  key_random([], []).
  key_random([H|T0], [K-H|T]) :-
       random(K),
       key_random(T0, T).

Even if random/1 is broken, returns constantly for example the value 0.97542354,
it will nevertheless give some permutation. Using random_permutation/2 to implement
random_indomain(X)  is straight forward:

       random_indomain(X) :-
              findall(Y, indomain0(X, Y), L),
              random_permutation(L, R),
              member(X, R).

indomain0/2 is a low-level predicate that enumerates X in the second argument without assigning it to X. The above considerations might not match SWI-Prologs CLP(FD) implementation, but I guess this is essentially what happens for ECLiPSe Prolog random option.

There is many to be demanded, like a benchmark test case, to see how efficiant this approach is. And then maybe implement something else, like Knuth shuffle. But Knuth shuffle is also hard, because for Prolog lists nth0/4 is not so efficient.

**Comment by jburse** [comment]
@Jan W. could close this issue. This was not a change request, there is no request to introduce random objects or whather. This was only a documentation request. But so far no documentation is available and also not in foreseeable future, so I guess this issue nees to be closed.

**Comment by jburse** [comment]
Closed this issue. Was not a change request, towards random objects or whatever. Only a documentation request, which by the discussion here is not available.
