### ISSUE TITLE
Support XDG path for configuration file

### ISSUE THREAD

**Issue by XVilka** [SWI-Prolog/swipl-devel#491]
Basically, to store it in `~/.config/SWI-Prolog/.swiplrc` or something similar. It resides in `$XDG_CONFIG_PATH` variable, so would look like `$XDG_CONFIG_PATH/SWI-Prolog/.swiplrc`.

**Comment by JanWielemaker** [comment]
Hmm.  Using `.swiplrc` in an already hidden directory seems weird.  The support for `XDG_CONFIG_PATH` doesn't seem widespread either.   I think we should follow standards unless there is a good reason not to.   I know `.config` is used by gnome.   I have the impression that ~/.myapprc is still the most common solution on Unix systems though.  Is there evidence this has changed?

**Comment by XVilka** [comment]
You can see the list of programs supporting new path scheme at Arch Linux wiki: https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by yochem** [comment]
I suggest `XDG_CONFIG_HOME/swi-prolog/init.pl` as pathname. This is based on neovim's config (`XDG_CONFIG_HOME/nvim/init.vim`). I think this is a better name because it's more of an initialisation file than a config file, and the `.pl` extensions helps text editors to recognize the right file format without using something like `% vim: ft=prolog` at the top of your file.

**Comment by JanWielemaker** [comment]
Moved discussion to forum at https://swi-prolog.discourse.group/t/location-of-personal-init-file-xdg-config-home/1301

**Comment by LyzardKing** [comment]
@JanWielemaker This can be closed after the last release(8.1.15), with the changes mentioned in the forum post.
