### ISSUE TITLE
Version number for latest stable release

### ISSUE THREAD

**Issue by xyproto** [SWI-Prolog/swipl-devel#62]
Hi,

Is there a web page where I can find the version number for the latest stable release?
https://github.com/SWI-Prolog/swipl-devel/blob/master/VERSION lists a different version number from https://github.com/SWI-Prolog/swipl-devel/blob/master/README, which is different from from http://www.swi-prolog.org/Download.html ("7.2.x"). There are also git repository tags, but they also differ (branch V732? tag XPCE-*? rel-*?).

Specifically, I'm trying to extract the version number automatically, so that I can package the latest stable version of SWI-Prolog for Arch Linux relatively quickly after a release has been made, but I can't find a good URL to use as a source for the version number.

Best regards,
   Alexander F Rødseth

**Comment by eazar001** [comment]
@xyproto 
I use these two:
http://www.swi-prolog.org/Download.html
http://www.swi-prolog.org/download/devel/src/

**Comment by xyproto** [comment]
It would be nice if the README file VERSION file had the same version number, though. Having git tags with only one version number system that also reflected the version number in the README + VERSION files would also bring some additional clarity here.

Suggestions for a hypothetical 7.3.5 release:

* 7.3.5 in the VERSION file
* A "v7.3.5" or "7.3.5" tag in the master branch. Possibly with a "stable" or "dev" branch or tag name prefix.
* "Version 7.3.5" in README, possibly without the latest update date, since this is recorded in git already (as opposed to `** Latest update: Aug 25, 2014 (Version 7.1.21)`)
* Listing 7.3.5 on the webpage, as opposed to 7.3.x.

Thanks for the links, though, @eazar001.

**Comment by eazar001** [comment]
@xyproto, yep. By the way there is also the stable repo: https://github.com/SWI-Prolog/swipl

**Comment by JanWielemaker** [comment]
On 06/30/2015 08:34 AM, Ebrahim Azarisooreh wrote:
> @xyproto <https://github.com/xyproto>, yep. By the way there is also the
> stable repo: https://github.com/SWI-Prolog/swipl

Yip. The `official' latest stable release version is in the VERSION file
of this repo. If this is 7.2.2, there is a tag V7.2.2, which is also
applied to all packages. Some packages have traditionally their own
version and tags. Separate package versions are no longer maintained.

(Wiki) web pages typically speak about 7.2.x to avoid having to update
them too often. The README file contains a "Latest update". That refers
to the latest update of the README file itself, which is quite rarely
updated.

If you want the latest tarball, you can download
http://www.swi-prolog.org/download/stable, search for a link to
swipl-*.tar.gz in the HTML page returned and download that. The download
links are automatically updated if a new version is uploaded.

	Cheers --- Jan

P.s.	The V733 branch exists because the master was updated by
	another commiter while I was preparing the 7.3.3 release.
	As a result I could not push to master :-(  Creating a
        branch was the only solution I could think of to push
	the V7.3.3 tag.
P.s.	Unlike previous messages, I'll probably release a 7.2.3
	due to a couple of small but important fixes.

**Comment by xyproto** [comment]
Ok, thanks for the explanation, and thanks for making and maintaining a quality Prolog compiler!
