### ISSUE TITLE
SWI-Prolog dialect syntax relaxation causes headache

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#666]
This would be a nice educational site,
if and only if, it were not written in
SWI-Prolog dialect:

**How to Build an Automated Theorem Prover**
http://www.jens-otten.de/tutorial_tableaux19/

Here is what is going wrong in the
SWI-Prolog dialect, and which causes
some unnessary headache.

Take this Prolog text:

    :- op(1110, xfy, =>).

Now observe:

Tau Prolog, this behaviour is Ok, I guess
the ISO core standard rather requires that:

    Tau Prolog 0.3.0 (beta)

    ?- X = prove(p => q).
    error parsing query:throw(error(syntax_error(', or ) expected'),[line(1),column(12),found(=>)]))

http://tau-prolog.org/sandbox/

SWI-Prolog, has provided a relaxation, I
do not think its ISO core standard conform:

    Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.6)

    ?- X = prove(p => p).
    X = prove((p=>p)).

The crazy thing about SWI-Prologs relaxation,
it still writes the parenthesis in the output.
It still writes `prove((p=>p))`.

I really do not have some words for this
incompatiblity. The Prolog text leanseq_v5.pl
cannot be entered in Tau Prolog as is,

because Jens Otten unknowingly used this
syntax relaxation feature of SWI-Prolog while
writing leanseq_v5.pl and unknowingly produced

Prolog code that isn't portable.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/implementing-quines-algorithm/2830/166

**Comment by JanWielemaker** [comment]
I see no problem.   The ISO standard somehow requires double parenthesis, but there is no meaningful ambiguity resolved by this demand.   This is a normal thing in not legally standardized languages.  gcc comes with many extensions to the C language, quite a few eventually being picked up by other compilers and sometimes eventually by the standard.    Without that process we would still live in the stone age.  We have a dead standardization process, so that is no option.   Otherwise I take improvements suggested by other Prolog systems serious.

If you want to limit yourself to producing a standard compliant program try to run it at least once on the most standard compliant implementation.    If you do not care too much some user will eventually complain and the maintainer can see what they consider more important.

And yes, SWI-Prolog tries to write terms in an ISO compliant format such that two Prolog processes can exchange terms using read/1 and write/1.   Of course this only applies to terms ISO Prolog can represent and not -for example- for rational numbers.

So, simply suggests Jens politely that an extra pair of parenthesis makes his program more portable and everything is solved.

**Comment by jburse** [comment]
It seems you guys want to see the world burn down. this is from joseph-vidal-rosset:
[quote="joseph-vidal-rosset, post:72, topic:2872"]
`[p => p]`
[/quote]
This aint working in GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/92714743-e0116a80-f35c-11ea-9c29-309ccb4fba6f.png)

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/improving-wangs-algorithm-in-prolog/2872/74

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/improving-wangs-algorithm-in-prolog/2872/80
