### ISSUE TITLE
Sequence tell/1, set_prolog_flag/2, tell/1 doesn't work

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#797]
Somehow interleaving doesn't work. Maybe because of some caching?
```
?- tell('/Users/janburse/Desktop/out.txt'), writeq('PHON:ˈteːnoːɐ̯'), told.
ERROR: I/O error in write on stream <stream>(0x6000003b5700) (Encoding cannot represent character)
?- told.
true.
?- set_prolog_flag(encoding, utf8).
true.
?- tell('/Users/janburse/Desktop/out.txt'), writeq('PHON:ˈteːnoːɐ̯'), told.
ERROR: I/O error in write on stream <stream>(0x6000003b5700) 
```
On the other hand when I have a fresh start, things work:
```
?- set_prolog_flag(encoding, utf8).
true.
?- tell('/Users/janburse/Desktop/out.txt'), writeq('PHON:ˈteːnoːɐ̯'), told.
true.
```

**Comment by JanWielemaker** [comment]
The first query raises an exception, gets back to the toplevel which switches the output stream back to user_output.   The told/0 on user_output has no effect (flushes the output) and this the subsequent tell/1 just reuses the same open stream as this is how tell is supposed to operate.   These predicates are pretty much broken by design.  I tried to ditch them, but that wasn't appreciated.
