### ISSUE TITLE
[Help needed] How to fix my Conan recipe?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#816]
# Context

I'm trying to create a Conan package for SWI-Prolog.  (The benefit of such a package is that dependencies can be installed within a separate cache and do not need to be installed system-wide (e.g. through apt on Ubuntu).  This makes it easier to use specific versions of packages, thereby (1) making it easier to use versions that are too new to be supported by the OS package manager, and (2) making it easier to use versions that are too old to be supported by the OS package manager.)

# Question

Does somebody know how to solve the following error:

```
/usr/bin/c++   -m64 -O3 -DNDEBUG  CMakeFiles/example.dir/example.cpp.o -o bin/example   -L/home/wouter/.conan/data/swipl/8.3.22/swipl/stable/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib  -Wl,-rpath,/home/wouter/.conan/data/swipl/8.3.22/swipl/stable/package/b173bbda18164d49a449ffadc1c9e817f49e819d/lib -lswipl 
gmake[2]: Leaving directory '/home/wouter/github/swipl-conan/test_package/build/8130ca333cc035689d4db02db920b56a5f995fbb'
[100%] Built target example
gmake[1]: Leaving directory '/home/wouter/github/swipl-conan/test_package/build/8130ca333cc035689d4db02db920b56a5f995fbb'
/usr/local/bin/cmake -E cmake_progress_start /home/wouter/github/swipl-conan/test_package/build/8130ca333cc035689d4db02db920b56a5f995fbb/CMakeFiles 0
swipl/8.3.22@swipl/stable (test package): Running test()
./example: error while loading shared libraries: libswipl.so.8: cannot open shared object file: No such file or directory
ERROR: swipl/8.3.22@swipl/stable (test package): Error in test() method, line 25
	self.run(".%sexample" % os.sep)
	ConanException: Error 127 while executing ./example
```

^ We see that `libswipl` is included correctly in the compile step, but an issue arises later when an example program is linked against the library.

# Steps to reproduce

1. `git clone https://github.com/wouterbeek/swipl-conan`
2. `conan create . swipl/stable -b missing`

**Comment by JanWielemaker** [comment]
Normally libswipl.so is found through the RPath compiled into the executable.   In the conanfile I see

    self.copy("*.so", dst="lib", src="src", keep_path=False)

This suggests the .so files are copied around?

**Comment by wouterbeek** [comment]
Hi Jan, yes you are right.

Conan performs the following steps, which for debugging purposes can be run in a terminal separately:

```
conan source     {project-root} -sf source                                   # Fetches sources.
conan install    {project-root} -if install                                  # Installs dependencies.
conan build      {project-root} -sf source -if install -bf build             # Compiles and links sources and dependencies.
conan package    {project-root} -sf source -if install -bf build -pf package # Creates the package locally.
conan export-pkg {project-root} -pf package                                  # Moves the package into the Conan cache.
conan test test_package {package}/{version}@{org}+{repo}/{channel}
```

^ In step `conan package` the relevant files must be copied over from the build directory into the package directory.

This is where the process seems to be quite different from other libraries/projects that I have created Conan packages for.  (But that is not saying much: my experience is quite limited.  Maybe the SWI-Prolog situation is more involved, simply because it is an inherently more complex project.)

Here are a couple of things that looked special to me:
  - The build step creates a `home` directory.  I have only seen a `home` directory as the parent directory for user directories on POSIX systems.  I have not seen it in a build before.
  - I saw that the compiled libraries were placed under the `src` directory by the build step.  I would have expected (only) source files and private header files there.
  - Many files are links to other locations.  This combined with the non-standard layout makes it difficult for me to understand what is where, and which is the right file for me to copy.
  - The public header files (e.g. `SWI-cpp.h`) include each other without project-specific prefix (e.g., `#include <SWI-Prolog.h>`).  This makes it more difficult to copy the public header files over.  Normally I would prefer to copy them into `include/swipl` to distinguish them from public header files from other projects upon system-wide installation.  I have seen projects with no project-specific subdirectory and one public header file, in which case I can copy that file from `include` to `include/{project}`.  I have also seen projects with multiple public header files within a project-specific subdirectory, in which case I can copy them from `include` to `include`.  I do not have experience with multiple public headers files that are not within a project-specific subdirectory.  Do you have ideas on how to deal with these?

For most of the projects that I have packaged before the package step consists of the following three things:

  1. Copy binaries from `bin` to `bin`.
  2. Copy public header files from `include` to `include`.
  3. Copy libraries from `lib` to `lib`.

^ I'm trying to find a mapping where the 'to' part is equally simple, but where the 'from' part connects to SWI-Prolog's build structure correctly.

**Comment by wouterbeek** [comment]
The chapter on "RPath" starts on page 378 of my CMake book.  I have not read it that far :-(  So I cannot comment to your remark regarding that concept yet.  I do see indeed that these are paths that are hard-coded into binaries?  That sounds like it could explain the observed behavior.

**Comment by JanWielemaker** [comment]
Projects like this are fairly complex.   The executable needs to find the libraries as well as extension _modules_ and the platform independent resources.   The extension modules must (on some platforms) also find the core `libswipl.*`.   You typically want multiple installations on a system.  Some systems want packages distributed over different directories, others in a single (position-independent) tree, etc.   

Several of these layouts are supported by the CMake scripts.   The rough idea is that the system accumulates the final set of libraries and other resources in `home`.   All the build products are placed where CMake places them by default and a local startup file is generated that allows running `src/swipl` in the build environment as a complete system (i.e., without installing).

The `install` (ninja or make) target installs everything outside the build tree in a location defined by the user and following a file system layout specified using CMake variables.   Don't try to copy files around yourself.   In most cases you'll break the mechanisms the various components are using to find each other.

The default setup creates a single self-contained tree and links the two main executables (`swipl` and `swipl-ld`) from the ``<prefix>/bin`` directory.   The RPath mechanism is used to allow the executables to find `libswipl` in the self-contained tree.  RPath basically adds an executable specific search path to the global library search paths for a specific executable.

You can use `-DSWIPL_INSTALL_IN_LIB=ON` to make it place `libswipl.so` in a directory and `-DSWIPL_INSTALL_IN_SHARE=ON` to install the docs in ``<prefix>/share``.  Installing `libswipl.so` globally simplifies embedding SWI-Prolog as the new executable doesn't have to worry about RPath issues.   It complicates version management though as `libswipl` does not follow the semantic version policy, but the SWI-Prolog version rules that care about compatibility at the Prolog level rather than compatibility of libswipl.so.   Notable existence, calling conventions and semantics of ``$``-predicates changes quite frequently.   This makes the libswipl.so of a version not usable with another version while it is should not affect any user.

As for the include files: do not move them around.   In you install them their name should be sufficiently unique, so adding `swipl` in between doesn't solve anything.   For example `swipl-ld` add the `include` dir of the self-contained tree to the search path.    Note that recent versions also create a CMake module that you can import into your project to link to the system.   I guess that should also work with conan.

For short, use `-DCMAKE_INSTALL_PREFIX` to set the target installation dir and one of the variables below to select the layout and use `make install` (better `ninja install`) to install the system.   You probably want to use the _PGO_ build step (`scripts/pgo-compile.sh`, only works with `ninja`) as that gives you an about 50% performance boost.

**Comment by wouterbeek** [comment]
Thanks for the extensive details Jan!  I'm not able to create a Conan package of this complexity myself.  It's purely a lack of knowledge on my side :-(  I'm hoping for a good Conan book to come out sometime soon.  Closing this issue for now...
