### ISSUE TITLE
`absolute_file_name/3` with `access(none)` still checks that file is not a directory

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#871]
When calling `absolute_file_name/3` with `access(none)` (the default), the file is actually still accessed to check its type. The call succeeds if the file either doesn't exist or is a regular file, but throws an error if it's a directory. This is a bit strange - one would expect that with `access(none)`, the file is never accessed at all, i. e. that the same result is returned regardless of what file might exist at the given path.

This behavior also differs from the [Quintus](https://quintus.sics.se/isl/quintus/html/quintus/mpg-ref-absolute_file_name.html#mpg-ref-absolute_file_name) and [SICStus](https://sicstus.sics.se/sicstus/docs/4.6.0/html/sicstus.html/mpg_002dref_002dabsolute_005ffile_005fname.html) versions of `absolute_file_name/3`, both of which specifically mention that if `access` is `none`, the directory check is *not* performed. The SWI documentation says that `absolute_file_name/3` is derived from the Quintus version, so this difference seems like a bug.

For even more confusion, `absolute_file_name/2` (with no option list) also accepts directories.

**Comment by JanWielemaker** [comment]
I addressed the `none` issue with 592327006e1162f42551d7a6380267c47a0a98cb

That at least fixes one issue for `absolute_file_name/2`.   Otherwise I'm not too sure about this.  `absolute_file_name/2` has a different history.   I'm tempted to deprecate it.   Ideally it should simply be `absolute_file_name/2` with an empty option list, but it prefers an existing file over a new entry.   What does SICStus do here?    All in all I think I never use `absolute_file_name/2` unless the first argument is an atom (no alias) as one almost always needs to specify the desired access.  Very occasionally one wants to examine the possible locations, but that requires `solutions(all)`.

**Comment by dgelessus** [comment]
As far as I can tell, on SICStus, `absolute_file_name(Path, Abs)` is completely equivalent to `absolute_file_name(Path, Abs, [])`. They document both on [the same manual page](https://sicstus.sics.se/sicstus/docs/4.6.0/html/sicstus.html/mpg_002dref_002dabsolute_005ffile_005fname.html) and I haven't encountered any differences between the two (although I haven't tried much).

Yeah, I already got the impression that SWI's `absolute_file_name/2` evolved independently from the Quintus/SICStus-like `absolute_file_name/3`. As a user this is a bit confusing - if a predicate exists both with and without an option list argument, then calling without an option list is usually the same as calling with an empty option list.

I personally don't need the 2-arg version anymore if the 3-arg version can now resolve paths without an access/type check. Whether you want to deprecate the 2-arg version is up to you, but it would be helpful if the documentation at least pointed out more clearly that the 2-arg and 3-arg versions are *not* equivalent.

**Comment by JanWielemaker** [comment]
I've updated the docs.   If you still see something wrong with it, just send a PR :smile:  Closing this one.
