### ISSUE TITLE
Error with library rbtrees

### ISSUE THREAD

**Issue by damianoazzolini** [SWI-Prolog/swipl-devel#903]
Hi.
I've just updated SWI to 8.5.2 (pull form this repo) and now, using the cplint package, i get the following error:
```
rbtrees:rb_lookup/3: No rule matches rbtrees:rb_lookup(_4030,t(black('',_4046,_4048,''),black('',_4046,_4048,'')),_4034)
rbtrees:rb_lookup/3: No rule matches rbtrees:rb_lookup(_6106,t(black('',_6122,_6124,''),black('',_6122,_6124,'')),_6110)
rbtrees:rb_lookup/3: No rule matches rbtrees:rb_lookup(_8100,t(black('',_8116,_8118,''),black('',_8116,_8118,'')),_8104)
rbtrees:rb_lookup/3: No rule matches rbtrees:rb_lookup(_1596,t(black('',_1612,_1614,''),black('',_1612,_1614,'')),_1600)
```
You can see this online with https://cplint.eu/example/inference/coin.pl by quering `prob(heads(coin),Prob).` (every query to every program throws this error).
Also version 8.5.1 has this problem. However, before upgrading SWI everithing was fine.
Unfortunately, I cannot tell which SWI version introduced this bug (my old version was still quite recent, I would say at most one month old).
Thanks.

**Comment by kamahen** [comment]
I modified the rbtree code so that an exception is thrown if the first argument is uninstantiated (the error message is a bit confusing - it's basically what the "=>" (single-sided unification) rule. And, looking at your outputs, it appears that the third argument ("Tree") is indeed uninstantiated. 
The commit: https://github.com/SWI-Prolog/swipl-devel/commit/0ad98034f88b1a316db637a599668d8a174aecca

I don't know what cpint is doing, but does it make sense to call rb_lookup/3 with the "Tree" uninstantiated? The definition is:
`rb_lookup(+Key, -Value, +Tree) is semidet`.

Previous behavior would have treated the uninstantiated "Tree" as a empty tree, I think. So, you can probably change your code from something like `rb_lookup(Key, Value, Tree)` to `rb_empty(Tree), rb_lookup(Key, Value, Tree)`. However, te definition of rb_lookup/3 also requires the Key to be instantiated, so that's probably still wrong.

Perhaps you should use rb_in/2 or rb_map?

**Comment by friguzzi** [comment]
Thanks Peter
We were using rbtrees for extracting variables from terms, we replace the code with term_variables/2.

Fabrizio

**Comment by JanWielemaker** [comment]
Much better :smile:   Seems Peter's improvement did catch a bug as the original code has swapped the 2nd and 3rd arguments.   Closing.
