### ISSUE TITLE
Top level reports negative changes in clause number

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/swipl-devel#95]
... on commit 4edc7c00a3008f332570472d50748cf2e8cf850e,  pretty much always. For example, loading a source file with exactly one predicate in it:

`foo.pl`

~~~~
foo :- true
~~~~

Then, load it:

~~~~
?- [foo].
true.
~~~~

Then, change it to:

~~~~
foo :- fail.
~~~~

~~~~
?- make.
% Updating index for library /home/boris/lib/swipl-7.3.12/library/
% /home/boris/code/foo compiled 0.00 sec, -1 clauses
~~~~

If you keep on alternating the two definitions, `make` will always report "-1 clauses".

You will get bigger negative numbers if you make bigger edits.

**Comment by JanWielemaker** [comment]
The number of clauses reported has become pretty much meaningless given the way the system handles reclaiming clauses.  It simply subtracts the clause statistics at end and start of the (re)load.  That was already dubious since compilation is multi-threaded and is now pretty much nonsense.  I don't know what to do yet.  Simply drop the clauses from the message or maintain a proper number with the source-file admin are the two serious options.

**Comment by borisvassilev** [comment]
Dropping them sounds like a good idea, but I don't know the reason why those are reported in the first place. Every time I have used `make` at the top level I have had to look at that number and wonder for a moment what to do with that information :)

**Comment by JanWielemaker** [comment]
Typically you have some expectations on what changes.  If the feedback tells a different story you have a clue that something went wrong.  I've implemented a reliable count with the source file administration.  I might at some point extend that to take advantage of the fact that the new reloading code tries to keep the old code and can thus produce diff-stat like feedback as in `clauses +10,-12`
to indicate that 10 new clauses were added and 12 were deleted.
